name: GLottery
version: 1.0
author: Godartm
main: fr.godartm.main.Main
description: Plugin de lotterie
depend: [Vault]

commands:
  loterie:
    description: Ouvre l'interface de loteries
    aliases: [lottery]
